In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
pd.set_option('display.float_format', lambda x: '%.5f' % x)


/home/eblics/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [20]:
df=pd.DataFrame(columns=['1','2'])
#df.columns=['1','2']

import struct
#str='2018.03.28,01:21,1.241090,1.240940,1.241120,1.241090'
#struct.unpack('10s1x5s1x8f1x8f1x8f1x8f1x',str)
#struct.unpack('8f',"1.241090")
s='1.241090'
a=struct.unpack('8s',s.encode())
a

(b'1.241090',)

In [23]:
s='2018.03.28,01:21,1.241090,1.240940,1.241120,1.241090'
import StringIO

ModuleNotFoundError: No module named 'StringIO'

In [49]:
a=np.array([1,2,3,5,3])
b=(a>2)*(a<5)
c=np.not_equal(b,1)
print(c)
#c=
#print(c)

[ True  True False  True False]


In [36]:
b=float('1.233')

In [57]:
a=np.random.randn(3,2,2)
print(a)
b=np.sum(a,axis=2,keepdims=1)
b

[[[-1.26686574  2.23101945]
  [ 0.97072195  0.87654712]]

 [[-0.48201427  0.02997364]
  [-1.36385137 -0.3123239 ]]

 [[-0.93646722 -0.39277967]
  [-0.24373101  0.34386939]]]


array([[[ 0.96415371],
        [ 1.84726906]],

       [[-0.45204062],
        [-1.67617527]],

       [[-1.32924689],
        [ 0.10013839]]])

In [146]:
df.columns=['date','time','open','high','low','close','vol']
k=0
s=0.0;sx=0.0;sy=0.0
gap=0.0
data=[]
index=0
for i in df.index:
    row=df.iloc[i]
    x=row['close']-row['open']
    y=row['high']-row['low']
    if s==0:s=x
    if s*x>=0 and abs(x)>0.00005:
        k+=1
        sx+=x
        sy+=y
    else:
        data.append([k,sx,sy,0,0,0])
        s=x
        if index>0:
            data[index-1][3]=k
            data[index-1][4]=sx
            data[index-1][5]=sy
        k=1;sx=x;sy=y;index+=1

In [33]:
ef.to_csv('pn.csv')

In [147]:
ef.columns=['pn','pco','phl','nn','nco','nhl']
ef.describe()

pn         pco         phl          nn         nco         nhl
count 44021.00000 44021.00000 44021.00000 44021.00000 44021.00000 44021.00000
mean      2.07828    -0.00000     0.00027     2.07826    -0.00000     0.00027
std       1.47579     0.00025     0.00030     1.47582     0.00025     0.00030
min       1.00000    -0.00662     0.00001     0.00000    -0.00662     0.00000
25%       1.00000    -0.00011     0.00011     1.00000    -0.00011     0.00011
50%       2.00000    -0.00001     0.00019     2.00000     0.00000     0.00019
75%       3.00000     0.00011     0.00034     3.00000     0.00011     0.00034
max      17.00000     0.00580     0.01850    17.00000     0.00580     0.01850

In [204]:
#gf=ef[(ef['pco']>0.00050) & (ef['pn']<=2)]
gf=ef[(ef['pco'])& (ef['phl']>=0.00100)]
p=len(gf[(gf['nco']<0)&(gf['nhl']>0.00020)].index)/len(gf.index)
p
#gf.describe()

0.7446351931330472

In [205]:
len(gf)

466

In [14]:
round(0.6)

1

In [32]:
a=np.array([[1],[2],[3]])
a=np.reshape(a,(3,))
a
#np.argmax(a)

array([1, 2, 3])

In [26]:
a[2]

array([3])

In [42]:
a=[3,2,1]
b=np.random.random(3,)
b

array([0.0135666 , 0.27569891, 0.88541955])

In [43]:
b=b<0.5

In [44]:
b

array([ True,  True, False])

In [45]:
a*b

array([3, 2, 0])

In [81]:
class A(object):
    def __init__(self):
        with tf.variable_scope("A", reuse=tf.AUTO_REUSE):
            self.v=tf.get_variable(name='a',shape=[3])
    def mul(self):
        self.v=tf.multiply(self.v,2)
a=A()
print(a.v)
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(a.v)

#saver=tf.train.Saver()
#saver.save(sess,'./A')

<tf.Variable 'A/a:0' shape=(3,) dtype=float32_ref>


array([-0.5781779 ,  0.62764263,  0.9527812 ], dtype=float32)

In [87]:
a.mul()
sess.run(a.v)
print(a.v)

Tensor("Mul_6:0", shape=(3,), dtype=float32)


In [83]:
saver=tf.train.Saver()
saver.save(sess,'./A')

'./A'

In [85]:
a=A()
sess.run(a.v)

array([-0.5781779 ,  0.62764263,  0.9527812 ], dtype=float32)

In [86]:
#sess.run(tf.global_variables_initializer())
saver.restore(sess,'./A')
sess.run(a.v)

INFO:tensorflow:Restoring parameters from ./A


array([-0.5781779 ,  0.62764263,  0.9527812 ], dtype=float32)

In [88]:
a=np.array([1,2,3])
a=a[:,np.newaxis]

In [89]:
a

array([[1],
       [2],
       [3]])