In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
pd.set_option('display.float_format', lambda x: '%.5f' % x)




/home/eblics/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
def weight_variable(shape):  
    # 正态分布，标准差为0.1，默认最大为1，最小为-1，均值为0  
    initial = tf.truncated_normal(shape, stddev=0.1)  
    return tf.Variable(initial)  
def bias_variable(shape):  
    # 创建一个结构为shape矩阵也可以说是数组shape声明其行列，初始化所有值为0.1  
    initial = tf.constant(0.1, shape=shape)  
    return tf.Variable(initial)  

In [4]:
initial = tf.truncated_normal([2,3], stddev=0.1)
w1=tf.Variable(initial)
w2=tf.Variable(tf.truncated_normal([2,3,2], stddev=0.1))
sess=tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(tf.matmul(w2,w1)))
#w2=sess.run(tf.nn.elu(w1))
#w3=sess.run(tf.nn.sigmoid(w2))


ValueError: Shape must be rank 2 but is rank 3 for 'MatMul' (op: 'MatMul') with input shapes: [2,3,2], [2,3].

In [17]:
w1

array([[ 0.01161465,  0.08005079, -0.01249805],
       [-0.17024335, -0.06269068, -0.03002963]], dtype=float32)

In [18]:
w2

array([[ 0.01161465,  0.08005079, -0.0124203 ],
       [-0.15654045, -0.06076604, -0.02958322]], dtype=float32)

In [19]:
w3

array([[0.50290364, 0.520002  , 0.49689493],
       [0.46094465, 0.48481318, 0.49260476]], dtype=float32)

In [107]:
a=np.arange(0,12)
a=a.reshape(2,3,2)
b=np.arange(0,2)
b=b.reshape(2,1)
c=a+b
c
#c

ValueError: operands could not be broadcast together with shapes (2,3,2) (2,1) 

In [99]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [106]:
b

array([[0, 1]])

In [76]:
c.shape

(2, 3, 3, 3)

In [81]:
a = np.array( [ [[ 1,2,3 ], [ 3,4,5 ], [5,6,7] ],
                [[1, 2, 3], [3, 4, 5], [5, 6, 7]],
                [[1, 2, 3], [3, 4, 5], [5, 6, 7]],
                [[1, 2, 3], [3, 4, 5], [5, 6, 7]]] )
b = np.array( [1,2,3] )
c=a*b


array([[[ 1,  4,  9],
        [ 3,  8, 15],
        [ 5, 12, 21]],

       [[ 1,  4,  9],
        [ 3,  8, 15],
        [ 5, 12, 21]],

       [[ 1,  4,  9],
        [ 3,  8, 15],
        [ 5, 12, 21]],

       [[ 1,  4,  9],
        [ 3,  8, 15],
        [ 5, 12, 21]]])

In [85]:
a=np.random.randn(4,3)

In [86]:
a

array([[ 1.95031883, -0.23440512,  0.74338463],
       [ 0.79233165, -1.45977429, -0.5771787 ],
       [-0.91593691, -0.52912707,  0.93170563],
       [ 1.13104852, -1.33949584, -0.40423781]])

In [87]:
a.mean(1)

array([ 0.81976611, -0.41487378, -0.17111945, -0.20422838])

In [89]:
b=a.mean(1).reshape(4,1)
b

array([[ 0.81976611],
       [-0.41487378],
       [-0.17111945],
       [-0.20422838]])