In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
pd.set_option('display.float_format', lambda x: '%.5f' % x)




/home/eblics/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [48]:
x=tf.placeholder(tf.float32,shape=[None,3])
w=tf.Variable(tf.random_normal(shape=[3,1],stddev=0.1))
b=tf.Variable(tf.random_normal(shape=[1],stddev=0.1))

y=tf.nn.xw_plus_b(x,w,b)
y=tf.nn.elu(y)
z=tf.zeros_like(y)
y=tf.greater(y,z)
y=tf.cast(y,tf.float32)
#y=tf.clip_by_value(y,0,3)
#z=tf.zeros_like(y)
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(y,feed_dict={x:[[1,-2,3],[4,5,6]]})

array([[0.],
       [1.]], dtype=float32)

In [46]:
y=tf.clip_by_value(y,0,3)
#sess=tf.Session()
#sess.run(tf.global_variables_initializer())
sess.run(y,feed_dict={x:[[1,-2,3],[4,5,6]]})


array([[1.],
       [1.]], dtype=float32)

In [56]:
x=tf.constant([1,2,3])
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(x)

array([1, 2, 3], dtype=int32)

In [57]:
z=tf.zeros_like(x)
y=tf.greater(x,z)
y=tf.cast(y,tf.float32)
#y=tf.clip_by_value(y,0,3)
#z=tf.zeros_like(y)
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(y,feed_dict={x:[[1,0,0],[4,5,6]]})

Dimension(3)