In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
pd.set_option('display.float_format', lambda x: '%.5f' % x)


/home/eblics/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [16]:
v=tf.Variable(tf.random_normal([5,3]))
u=tf.Variable(tf.random_normal([3,1]))
#o2=sess.run(elu)

In [30]:
#elu=tf.nn.elu(v)
v=tf.Variable(tf.random_normal([5,3]))
u=tf.Variable(tf.random_normal([3,1]))
mat=tf.matmul(v,u)


In [31]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())
o1=sess.run(v)

In [32]:
o1

array([[ 0.05625284, -0.13630888, -0.49431455],
       [-1.3645667 , -1.2147046 , -1.3903712 ],
       [ 1.4511695 ,  1.0732796 ,  0.03041387],
       [ 0.37042356, -0.30411425, -0.38280645],
       [ 0.42758554,  0.13371573, -1.7803665 ]], dtype=float32)

In [33]:
o2=sess.run(u)

In [34]:
o2

array([[-0.20358418],
       [-0.6987257 ],
       [-0.20538548]], dtype=float32)

In [35]:
o3=sess.run(mat)

In [36]:
o3

array([[ 0.18531536],
       [ 1.4121115 ],
       [-1.0516098 ],
       [ 0.21570295],
       [ 0.18518117]], dtype=float32)

In [37]:
elu=tf.nn.elu(mat)
o4=sess.run(elu)

In [38]:
o4

array([[ 0.18531536],
       [ 1.4121115 ],
       [-0.6506251 ],
       [ 0.21570295],
       [ 0.18518117]], dtype=float32)

In [43]:
sg=tf.nn.sigmoid(elu)
o5=sess.run(sg)

In [46]:
ag=tf.argmax(sg)
o6=sess.run(ag)

In [49]:
o5

array([[0.5461967 ],
       [0.8040988 ],
       [0.3428487 ],
       [0.5537176 ],
       [0.54616344]], dtype=float32)

In [50]:
te=tf.equal([0,1,0,1],[0,0,0,0])
sess.run(te)

array([ True, False,  True, False])

In [52]:
rm=tf.reduce_mean(tf.cast(te,tf.float32))
sess.run(rm)

0.5

In [60]:
sess.run(tf.argmax([[1,2,3,4],[5,2,3,4]],1))

array([3, 0])

In [67]:
sess.run(tf.nn.softmax([0.2,3.1,4.2,5.1]))

array([0.00480626, 0.08734963, 0.2624128 , 0.64543134], dtype=float32)

In [68]:
a=np.array([5,3])

In [70]:
a=np.zeros([100])
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
d1=pd.DataFrame([1,2,3,4,5])


In [72]:
d1[0:2]

0
0  1
1  2

In [75]:
a=np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [79]:
b=a.transpose((1,0))
b

array([[0, 3],
       [1, 4],
       [2, 5]])

In [80]:
a=[1,1,0]
b=[2,3,2]
c=a*np.log(b)
c

array([0.69314718, 1.09861229, 0.        ])

In [82]:
d=np.sum(c)

In [83]:
d

1.791759469228055