In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
import sys
import time
pd.set_option('display.float_format', lambda x: '%.5f' % x)
np.set_printoptions(suppress=True,precision=6)




/home/eblics/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [18]:
a=tf.Variable(tf.constant(2,tf.float32,[3,3]))
b=tf.assign(a[0],tf.constant(1,tf.float32,[3]))
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(b)

array([[1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]], dtype=float32)

In [21]:
tf.reset_default_graph()
w1=tf.placeholder(shape=[None],dtype=tf.float64)
b1=tf.constant(np.random.random((3,5)))

i=tf.constant(3)

def cond(x):
    if x<5:return False
    else:return True

def body(x):
    x+=1
    def succ():
        s=w1[x-2:x]
        return s*2
    def fail():
        return w1
    tf.cond(x>2,succ,fail)
    return x


    
    #tf.cond(x>2,lambda y:y,lambda y:y+1)
#y=tf.cond(i<3,lambda:tf.add(i,1),lambda:tf.add(i,2))    
loop=tf.while_loop(cond,body,[i])
sess=tf.Session()
sess.run(tf.global_variables_initializer())
data=np.random.random((10,))
#print(sess.run(tf.size(w1)))
print(sess.run(loop,feed_dict={w1:data}))
#print(sess.run(y))

TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

In [7]:
df=pd.read_csv('test.csv.bak',header=None)
print(df.iloc[0][0])

2017.11.01


In [164]:
w1=tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
w2=tf.constant([[[1],[2]],[[3],[4]]])
x=tf.constant([1,2,3])
y1=w1*x
y2=tf.reduce_sum(y1,2,keepdims=True)
y3=w2*y2
y4=tf.reduce_sum(y3,1)
#c=tf.multiply(a,b)
#d=tf.reduce_sum(c,[2],keepdims=True)
#e=tf.multiply(b2,d)
#m=tf.greater(m,0.2)
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run([y1,y2,y3,y4])

[array([[[ 1,  2,  3],
         [ 2,  4,  6]],
 
        [[ 3,  6,  9],
         [ 4,  8, 12]]], dtype=int32), array([[[ 6],
         [12]],
 
        [[18],
         [24]]], dtype=int32), array([[[ 6],
         [24]],
 
        [[54],
         [96]]], dtype=int32), array([[ 30],
        [150]], dtype=int32)]

In [24]:
import tensorflow as tf

n = 10000
x = tf.constant(list(range(n)))
c = lambda i, x: i < n
b = lambda i, x: (tf.Print(i + 1, [i]), tf.Print(x + 1, [i], "x:"))
i, out = tf.while_loop(c, b, (0, x))
with tf.Session() as sess:
    #print(sess.run(i))  # prints [0] ... [9999]

    # The following line may increment the counter and x in parallel.
    # The counter thread may get ahead of the other thread, but not the
    # other way around. So you may see things like
    # [9996] x:[9987]
    # meaning that the counter thread is on iteration 9996,
    # while the other thread is on iteration 9987
    print(sess.run(out))

[10000 10001 10002 ... 19997 19998 19999]


In [17]:
w1

array([[ 0.01161465,  0.08005079, -0.01249805],
       [-0.17024335, -0.06269068, -0.03002963]], dtype=float32)

In [18]:
w2

array([[ 0.01161465,  0.08005079, -0.0124203 ],
       [-0.15654045, -0.06076604, -0.02958322]], dtype=float32)

In [19]:
w3

array([[0.50290364, 0.520002  , 0.49689493],
       [0.46094465, 0.48481318, 0.49260476]], dtype=float32)

In [29]:
a=tf.constant(np.random.random((10)))
b=tf.constant(np.random.random((10)))
a=tf.cast(tf.greater(a,0.1),tf.int32)
b=tf.cast(tf.greater(b,0.1),tf.int32)
c=a*b
sess=tf.Session()
sess.run(c)

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 0], dtype=int32)

In [172]:
np.random.randint(-1,2,(2,3))

array([[ 1, -1, -1],
       [-1,  1,  1]])

In [106]:
b

array([[0, 1]])

In [76]:
c.shape

(2, 3, 3, 3)

In [81]:
a = np.array( [ [[ 1,2,3 ], [ 3,4,5 ], [5,6,7] ],
                [[1, 2, 3], [3, 4, 5], [5, 6, 7]],
                [[1, 2, 3], [3, 4, 5], [5, 6, 7]],
                [[1, 2, 3], [3, 4, 5], [5, 6, 7]]] )
b = np.array( [1,2,3] )
c=a*b


array([[[ 1,  4,  9],
        [ 3,  8, 15],
        [ 5, 12, 21]],

       [[ 1,  4,  9],
        [ 3,  8, 15],
        [ 5, 12, 21]],

       [[ 1,  4,  9],
        [ 3,  8, 15],
        [ 5, 12, 21]],

       [[ 1,  4,  9],
        [ 3,  8, 15],
        [ 5, 12, 21]]])

In [85]:
a=np.random.randn(4,3)

In [86]:
a

array([[ 1.95031883, -0.23440512,  0.74338463],
       [ 0.79233165, -1.45977429, -0.5771787 ],
       [-0.91593691, -0.52912707,  0.93170563],
       [ 1.13104852, -1.33949584, -0.40423781]])

In [87]:
a.mean(1)

array([ 0.81976611, -0.41487378, -0.17111945, -0.20422838])

In [89]:
b=a.mean(1).reshape(4,1)
b

array([[ 0.81976611],
       [-0.41487378],
       [-0.17111945],
       [-0.20422838]])

In [6]:
import numpy as np

z=np.random.rand(2,3)
a=z>0.5
b=z*a
b

array([[0.        , 0.74570403, 0.        ],
       [0.        , 0.5410107 , 0.56452181]])

In [4]:
z

array([[0.28317816, 0.42779309, 0.49443431],
       [0.72035771, 0.20999469, 0.115658  ]])

In [5]:
z=z>0.5
z

array([[False, False, False],
       [ True, False, False]])

In [7]:
a=[0 for i in range(0,10)]

In [8]:
a

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [16]:
class A(object):
    def __init__(self):
        self.a=1
        pass
a=np.array([A()])
a=a['a']>0
a

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

import pandas as pd
df=pd.read_csv('1.csv',header=None)
df['co']=(df['close']-df['open'])*10000

In [20]:
import pandas as pd
df=pd.read_csv('1.csv',header=None)
df.columns=['date','time','open','high','low','close','volume']
df['co']=(df['close']-df['open'])*100000

In [32]:
ef=df[abs(df['co'])>15]
ef.size/df.size

0.1089713332703987

0.026936026936026935

In [41]:
a=[1,2,3,4,5,6]
for i in range(0,len(a)):
    del a[i]

IndexError: list assignment index out of range

In [20]:
a=np.array([1,2,3,4])
a[0:1]

array([1])

In [44]:
import math
a=math.rand(1,2)

AttributeError: module 'math' has no attribute 'rand'

In [60]:
import numpy as np
a=np.random.randint(1,10,10)
a=a/10
a

array([0.4, 0.9, 0.2, 0.7, 0.4, 0.6, 0.7, 0.4, 0.2, 0.2])

In [68]:
class child(object):
    def __init__(self,parent,i):
        self.parent=parent
        self.i=i
    def open(self):
        self.parent.childs.append(self)
    def close(self):
        self.parent.childs.remove(self)
class parent(object):
    def __init__(self):
        self.childs=[]
p=parent()
for i in range(0,10):
    a=child(p,i)
    a.open()

#len(p.childs)

In [76]:
class A(object):
    def __init__(self,i):
        self.i=i

a=[A(i) for i in range(0,10)]
b=sum([c.i for c in a])


In [77]:
b

45

In [78]:
round(0.2)

0

In [79]:
round(0.02)

0

In [80]:
a=np.random.randn(30)

In [81]:
a


array([-0.20955349,  0.2465717 ,  0.63334801,  0.35708518, -0.46109937,
        0.32533576, -1.08827063, -0.11201618,  1.40697713,  1.25999537,
       -0.93177016, -1.30222875,  0.07475378,  0.4698799 ,  0.35432827,
       -0.67064298,  1.60726929,  0.31753321, -0.34511446, -0.13711694,
        0.09852977, -0.2849398 ,  0.59484068, -0.50311712, -0.19622582,
        0.70315728, -2.14850171,  1.48206994,  0.46436493,  0.60307547])

In [90]:
import math
a=np.random.randn(3,4)

In [91]:
a

array([[ 1.88079959,  1.60863101,  0.01139274, -0.68371673],
       [-1.04276196,  0.48655003,  0.87044045, -1.98907755],
       [ 0.10381802, -1.41818973,  2.55899101,  0.20833881]])

array([0.76852478, 0.96770454])

In [98]:
a=[1,2,3,4]
b=a[np.random.randint(0,len(a))]
b

3

In [33]:
b=tf.constant(np.random.random((50)))
s=tf.reduce_all(tf.less_equal(b,8))
sess=tf.Session()
print(sess.run(b))
sess.run(s)

[0.109756 0.514042 0.157302 0.947514 0.323329 0.490191 0.490457 0.600655
 0.368815 0.92555  0.955406 0.977309 0.176411 0.004199 0.844966 0.54571
 0.157843 0.543775 0.080446 0.67585  0.761855 0.444664 0.97134  0.018185
 0.295807 0.818411 0.344486 0.247867 0.635323 0.503981 0.307775 0.736778
 0.788411 0.407393 0.37124  0.90185  0.163313 0.352164 0.171078 0.562573
 0.463789 0.850713 0.167648 0.781631 0.738957 0.054768 0.384162 0.937871
 0.639048 0.494242]


True

In [35]:
a=np.random.randn(30)
b=a*(a>0.1)
b

array([-0.      , -0.      ,  0.805944,  1.120139, -0.      , -0.      ,
       -0.      , -0.      ,  0.801498,  0.      , -0.      ,  1.873072,
        0.949464,  2.300918,  1.425618, -0.      ,  0.324347, -0.      ,
       -0.      , -0.      , -0.      ,  0.346548, -0.      , -0.      ,
       -0.      , -0.      ,  0.677577,  1.520295,  2.450291, -0.      ])